apiVersion: v1
entries:
  kanbanapp-demo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-07-07T03:39:55.729493-05:00"
    description: A Helm chart for Kubernetes
    digest: f41ceffe684070d3a35e08ae16f31488a99f0ca0a5b4241dd49238885e759ad1
    name: kanbanapp-demo
    type: application
    urls:
    - https://sdandey.github.io/kanbanapp-helmcharts/charts/kanbanapp-demo-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-07-07T03:39:55.728515-05:00"
    description: A Helm chart for Kubernetes
    digest: 91fe9f3b0032db89ce3c6c2b0754f181268986129ff45a1366c5b02125d54a22
    name: kanbanapp-demo
    type: application
    urls:
    - https://sdandey.github.io/kanbanapp-helmcharts/charts/kanbanapp-demo-0.2.0.tgz
    version: 0.2.0
generated: "2021-07-07T03:39:55.727093-05:00"
